#!/usr/bin/env bash
# Bench + ncu capture for chapter 01 vector_add.
#
# Output: 01_vector_add.csv (raw ncu dump) + 01_vector_add.md (summary).

set -euo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$here/common.sh"

binary="$BUILD_DIR/01_vector_add"
csv="$here/01_vector_add.csv"
md="$here/01_vector_add.md"
typ="$here/01_vector_add.typ"

# rebuild to make sure binary is up to date
make -C "$REPO_ROOT" "$binary" >/dev/null

# All five kernels, one metric set.  Memory-bound => we care about DRAM %,
# SM active %, kernel time.
kernel_regex='regex:vector_add'

metrics='gpu__time_duration.sum,dram__bytes.sum.pct_of_peak_sustained_elapsed,dram__bytes.sum,sm__cycles_active.avg.pct_of_peak_sustained_elapsed,launch__grid_size,launch__block_size,launch__registers_per_thread'

ncu_metrics "$binary" "$kernel_regex" "$csv" "$metrics"

# Extract a compact table: kernel, grid, block, regs, time_us, dram_pct, sm_pct, effective GBps
python3 - "$csv" "$md" "$typ" <<'PY'
import csv, sys, re, collections

csv_path, md_path, typ_path = sys.argv[1], sys.argv[2], sys.argv[3]

# ncu prints "==PROF==" lines to the log file before the actual csv header.
# Skip anything before the "ID","Process ID"... header.
raw = open(csv_path).read().splitlines()
for i, line in enumerate(raw):
    if line.startswith('"ID"'):
        raw = raw[i:]
        break
csv_text = "\n".join(raw)
import io
csv_stream = io.StringIO(csv_text)

# Problem size hard-coded to match src/cuda/01_vector_add.cu main().
# N floats read from a, read from b, written to c => 3*N*4 bytes moved.
N = 1 << 20
bytes_per_launch = 3 * N * 4  # baseline for the scalar kernels

# vectorized (non-fused) also processes vector_count*4 floats in main + tail
# separately; the fused kernel does the whole N in one launch.  For simplicity
# we report the *effective* GB/s based on N*3*4 for every kernel version --
# that's what the user cares about (throughput on the same problem).

rows = []
if True:
    reader = csv.DictReader(csv_stream)
    # ncu output: rows are (kernel, metric_name, metric_value).  Pivot to wide.
    by_kernel = collections.defaultdict(dict)
    order = []
    for r in reader:
        k = r['Kernel Name']
        if k not in by_kernel:
            order.append(k)
            by_kernel[k]['_grid'] = r.get('Grid Size', '')
            by_kernel[k]['_block'] = r.get('Block Size', '')
        by_kernel[k][r['Metric Name']] = (r['Metric Value'], r.get('Metric Unit', ''))

def short(k):
    m = re.search(r'vector_add_(\w+?)_kernel', k)
    return m.group(1) if m else k

def num(v):
    return float(v.replace(',', ''))

# Rebuild pretty table.
lines = []
lines.append("| version | grid | block | regs | time (μs) | HBM % | SM active % | effective GB/s |")
lines.append("|---|---|---|---|---|---|---|---|")
for k in order:
    d = by_kernel[k]
    if 'gpu__time_duration.sum' not in d:
        continue
    time_ns = num(d['gpu__time_duration.sum'][0])
    time_us = time_ns / 1e3
    hbm_pct = num(d['dram__bytes.sum.pct_of_peak_sustained_elapsed'][0])
    sm_pct = num(d['sm__cycles_active.avg.pct_of_peak_sustained_elapsed'][0])
    regs = d.get('launch__registers_per_thread', ('?', ''))[0]
    grid = d.get('_grid', '?')
    block = d.get('_block', '?')
    gbps = bytes_per_launch / time_ns  # bytes/ns == GB/s
    lines.append(f"| {short(k)} | {grid} | {block} | {regs} | {time_us:.2f} | {hbm_pct:.1f} | {sm_pct:.1f} | {gbps:.1f} |")

with open(md_path, 'w') as f:
    f.write("<!-- Auto-generated by bench/01_vector_add.sh -->\n")
    f.write("<!-- Hardware: A100 80GB SXM4, CC 8.0, HBM peak ~2039 GB/s -->\n")
    f.write("<!-- Problem: N = 2^20 floats (3 arrays, 12 MB total) -->\n\n")
    f.write("\n".join(lines) + "\n")

# Also emit a typst table so the book can `#include` it directly.
typ_lines = []
typ_lines.append("// Auto-generated by bench/01_vector_add.sh.  Do not edit.")
typ_lines.append("// Hardware: A100 80GB SXM4 (CC 8.0), HBM peak ~2039 GB/s")
typ_lines.append("// Problem: N = 2^20 floats, 3 arrays => 12 MB moved per kernel")
typ_lines.append("")
typ_lines.append("#table(")
typ_lines.append("  columns: (auto, auto, auto, auto, auto, auto, auto),")
typ_lines.append("  stroke: 0.5pt + gray, inset: 6pt,")
typ_lines.append("  align: (left, right, right, right, right, right, right),")
typ_lines.append("  [*version*], [*regs*], [*time (μs)*], [*HBM %*], [*SM %*], [*GB/s*], [*% peak*],")
for k in order:
    d = by_kernel[k]
    if 'gpu__time_duration.sum' not in d:
        continue
    time_ns = num(d['gpu__time_duration.sum'][0])
    time_us = time_ns / 1e3
    hbm_pct = num(d['dram__bytes.sum.pct_of_peak_sustained_elapsed'][0])
    sm_pct = num(d['sm__cycles_active.avg.pct_of_peak_sustained_elapsed'][0])
    regs = d.get('launch__registers_per_thread', ('?', ''))[0]
    gbps = bytes_per_launch / time_ns
    peak_pct = gbps / 2039 * 100
    typ_lines.append(
        f"  [{short(k).replace('_','-')}], [{regs}], [{time_us:.2f}], "
        f"[{hbm_pct:.1f}], [{sm_pct:.1f}], [{gbps:.0f}], [{peak_pct:.1f}],"
    )
typ_lines.append(")")

with open(typ_path, 'w') as f:
    f.write("\n".join(typ_lines) + "\n")

print(open(md_path).read())
PY

echo "wrote $md"
